#!/bin/bash
# Apply the three staging-pin files in one shot. Idempotent — re-runnable
# against any origin/main HEAD because the output is a pure function of
# the env vars below.
#
# Used by .github/workflows/build-deploy.yml twice:
#   1. Once before the first push attempt.
#   2. Again after `git reset --hard origin/main` if the first push
#      lost a race to another auto-pin job. The reset blows away the
#      conflict; this script writes the same pin against the new HEAD,
#      yielding a clean fast-forward push.
#
# Required env:
#   VERSION       — semver-ish, e.g. "0.1.0-2a3e9fd"
#   BRANCH        — ref short name, e.g. "main"
#   BACKEND_TAG   — image tag, e.g. "20260526200325-2a3e9fd" (may be empty
#                   if backend build was skipped — pin then no-ops for it)
#   ADMIN_TAG     — same shape
#   TENANT_TAG    — same shape
#
set -euo pipefail

: "${VERSION:?VERSION must be set}"
: "${BRANCH:?BRANCH must be set}"

OVERLAY=k8s/overlays/staging
mkdir -p "$OVERLAY"

# ─── 1. platform-version ConfigMap patch ───
cat > "$OVERLAY/platform-version-patch.yaml" <<PATCH
# Auto-generated by .github/workflows/build-deploy.yml on each
# main-branch push. Do not edit by hand — edits will be overwritten.
apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-version
  namespace: platform
data:
  version: "${VERSION}"
  branch: "${BRANCH}"
PATCH

# Ensure the patch is referenced from kustomization.yaml. Idempotent —
# only inserts the line if it isn't already present.
if ! grep -q "platform-version-patch.yaml" "$OVERLAY/kustomization.yaml"; then
  sed -i '/^patches:/a\  - path: platform-version-patch.yaml' "$OVERLAY/kustomization.yaml"
fi

# ─── 2. deploy-rev annotation patch (rolls 3 Deployments + 2 DaemonSets) ───
cat > "$OVERLAY/deploy-rev-patch.yaml" <<PATCH
# Auto-generated by .github/workflows/build-deploy.yml on each
# main-branch push — the annotation changes with every VERSION
# so Flux rolls the pod, which picks up the latest :latest
# image and the current platform-version ConfigMap value.
# Do not edit by hand — edits will be overwritten.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-api
  namespace: platform
spec:
  template:
    metadata:
      annotations:
        platform.example.test/deploy-rev: "${VERSION}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-panel
  namespace: platform
spec:
  template:
    metadata:
      annotations:
        platform.example.test/deploy-rev: "${VERSION}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-panel
  namespace: platform
spec:
  template:
    metadata:
      annotations:
        platform.example.test/deploy-rev: "${VERSION}"
---
# firewall-reconciler — :latest-tagged DaemonSet that needs
# rolling on every push so the new image SHA is picked up
# (imagePullPolicy: Always on the container).
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: firewall-reconciler
  namespace: platform-system
spec:
  template:
    metadata:
      annotations:
        platform.example.test/deploy-rev: "${VERSION}"
---
# mail-stack-standby-replicate — :latest-tagged DaemonSet
# (mail-backup-tools image) — same rationale as above. New
# script changes in images/mail-backup-tools/ are baked into
# :latest by ci-mail-backup-tools.yml; this annotation
# ensures the running Pods restart to pick them up.
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mail-stack-standby-replicate
  namespace: mail
spec:
  template:
    metadata:
      annotations:
        platform.example.test/deploy-rev: "${VERSION}"
PATCH

# ─── 3. Image tags in kustomization.yaml `images:` block ───
# Replaces the work Flux's image-automation-controller used to do via a
# long-lived PAT. The IUA approach failed silently when the PAT expired,
# so doing the rewrite from CI uses the ephemeral GITHUB_TOKEN already
# scoped for repo write — no PAT to rotate.
KUST="$OVERLAY/kustomization.yaml"
pin() {
  local image=$1 tag=$2
  if [[ -z "$tag" ]]; then
    echo "skip $image (no tag — build was skipped)"
    return
  fi
  # sed N;s/.../.../ pairs the matched `name: ...` line with the next
  # `newTag: "..."` line, then rewrites the tag in the paired buffer.
  # Anchoring `name` with a $-end marker avoids matching within a
  # "newTag" comment.
  sed -i -e "/name: ghcr\.io.*\/${image}\$/{N;s/newTag: \"[^\"]*\"/newTag: \"${tag}\"/}" "$KUST"
  echo "pinned ${image} → ${tag}"
}
pin backend       "${BACKEND_TAG:-}"
pin admin-panel   "${ADMIN_TAG:-}"
pin tenant-panel  "${TENANT_TAG:-}"

echo "---kustomization newTag lines after pin---"
grep -B1 newTag "$KUST" | grep -E "name: ghcr|newTag" || true
