#!/usr/bin/env python3
"""Render the weekly component-watch tracking issue body (Markdown).

Usage: component-watch-sweep.py <osv.json> <latest.json> <components.yaml> <cve-ledger.yaml>

Sections: open ledger items (with SLA flag), new OSV HIGH/CRITICAL findings,
components behind upstream. Part of ADR-050; consumed by component-watch.yml.
"""
import datetime
import json
import sys

OPEN_STATUSES = {"open", "investigating", "mitigated"}
TRACKED_STATUSES = {"open", "investigating", "mitigated", "not_affected",
                    "accepted", "fixed"}
SLA_DAYS = {"0": 2, "1": 7, "2": 30, "3": None, "C": 7, "X": None}


def load_json(path):
    try:
        with open(path) as f:
            return json.load(f)
    except (OSError, json.JSONDecodeError):
        return None


def main() -> int:
    if len(sys.argv) < 5:
        print(f"Usage: {sys.argv[0]} <osv.json> <latest.json> <components.yaml> <cve-ledger.yaml>",
              file=sys.stderr)
        return 2
    osv_p, latest_p, comps_p, ledger_p = sys.argv[1:5]
    import yaml

    osv = load_json(osv_p) or {}
    latest = load_json(latest_p) or []
    comps = (yaml.safe_load(open(comps_p)) or {}).get("components", [])
    by_id = {c["id"]: c for c in comps}
    ledger = (yaml.safe_load(open(ledger_p)) or {}).get("entries", []) or []
    today = datetime.date.today()

    out = []
    out.append(f"_Auto-generated by `component-watch.yml` on {today.isoformat()} "
               f"(ADR-050). Triage items below; this issue is updated in place each week._\n")

    # ── open ledger items ──
    open_items = [e for e in ledger if e.get("status") in OPEN_STATUSES]
    out.append(f"## Open ledger items ({len(open_items)})\n")
    if not open_items:
        out.append("None. 🎉\n")
    else:
        out.append("| CVE | Component | Tier | Severity | Status | SLA |")
        out.append("|---|---|---|---|---|---|")
        for e in sorted(open_items, key=lambda e: str(e.get("severity"))):
            comp = e.get("component", "?")
            tier = str(by_id.get(comp, {}).get("tier", "?"))
            days = SLA_DAYS.get(tier)
            sla = "—"
            disc = e.get("discovered")
            if days is not None and disc and (e.get("kev") or e.get("severity") == "critical"):
                try:
                    d = datetime.date.fromisoformat(str(disc))
                    age = (today - d).days
                    sla = f"⏰ {age}/{days}d" + (" **OVERDUE**" if age > days else "")
                except ValueError:
                    sla = "?"
            out.append(f"| {e.get('id')} | {comp} | {tier} | {e.get('severity')} "
                       f"| {e.get('status')} | {sla} |")
        out.append("")

    # ── new OSV HIGH/CRITICAL findings ──
    tracked = {str(e.get("id")) for e in ledger
               if e.get("status") in TRACKED_STATUSES and e.get("id")}
    findings = []
    for r in osv.get("results", []):
        src = (r.get("source") or {}).get("path", "?")
        for pkg in r.get("packages", []):
            name = (pkg.get("package") or {}).get("name", "?")
            for grp in pkg.get("groups", []):
                ids = set(grp.get("ids", [])) | set(grp.get("aliases", []))
                if ids & tracked:
                    continue
                try:
                    score = float(grp.get("max_severity", ""))
                except (TypeError, ValueError):
                    score = None
                if score is None or score >= 7.0:
                    findings.append((grp.get("ids", ["?"])[0], name, src,
                                     grp.get("max_severity", "?")))
    out.append(f"## Untracked dependency findings — HIGH/CRITICAL ({len(findings)})\n")
    if not findings:
        out.append("None.\n")
    else:
        out.append("| ID | Package | CVSS | Source |")
        out.append("|---|---|---|---|")
        for vid, name, src, sev in findings:
            out.append(f"| {vid} | {name} | {sev} | `{src}` |")
        out.append("\n> Add a ledger entry in `security/cve-ledger.yaml` for each "
                   "(triage → mitigated/not_affected/accepted, or fix the dep).\n")

    # ── components behind upstream ──
    behind = [r for r in latest if r.get("behind")]
    out.append(f"## Components behind upstream ({len(behind)})\n")
    if not behind:
        out.append("All watched components are current (or unverified).\n")
    else:
        out.append("| Component | Tier | Pinned | Upstream |")
        out.append("|---|---|---|---|")
        for r in sorted(behind, key=lambda r: str(r.get("tier"))):
            out.append(f"| {r.get('id')} | {r.get('tier')} | "
                       f"`{r.get('pinned')}` | `{r.get('latest')}` |")
        out.append("")

    out.append("\n---\n_Process: [docs/operations/COMPONENT_WATCH.md]"
               "(../blob/main/docs/operations/COMPONENT_WATCH.md)_")
    print("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
