-- Node reboot lifecycle (operator request 2026-09-11).
--
-- `boot_id` is the kubelet's status.nodeInfo.bootID — regenerated by the kernel
-- on every boot, so a change is proof the machine rebooted (a kubelet restart or
-- a NotReady flap leaves it untouched). `reboot_announced` records whether a
-- "node is rebooting" notice already went out for the CURRENT boot, so the
-- startup notification can say whether the operator was warned — on a
-- single-node cluster the control plane goes down with the node and usually
-- cannot announce its own shutdown.
--
-- Both nullable/defaulted: existing rows adopt the live bootID on the next
-- reconcile tick WITHOUT reporting a reboot (detectBootTransitions requires a
-- previous bootID before it will claim one).
ALTER TABLE node_health_state
  ADD COLUMN IF NOT EXISTS boot_id TEXT,
  ADD COLUMN IF NOT EXISTS reboot_announced BOOLEAN NOT NULL DEFAULT FALSE;
