/**
 * Multi-host vhost renderer — turns `ingress_routes` rows into the web-server
 * config that makes one pod answer several hostnames, each from its own folder.
 *
 * PURE on purpose. Everything that decides what a tenant's web server is told
 * to do happens here, with no cluster and no database, so the whole surface is
 * unit-testable and the reconciler only has to deliver bytes.
 *
 * Two invariants this file owns:
 *
 *  1. **The platform renders the config; the catalog never supplies it.** A
 *     manifest declares which flavour and where the files go, and admins can
 *     add third-party catalog repositories — so a repo that could hand us vhost
 *     TEXT would be handing us arbitrary directives inside a tenant's server.
 *
 *  2. **Nothing reaches the config that has not been re-validated here.**
 *     Hostnames and folders are already checked at the API, but this is the
 *     last gate before text becomes directives, and a newline in either would
 *     be config injection rather than a bad value.
 */

import { wwwRedirectHosts } from '../ingress-routes/traefik-types.js';
import { folderProblem } from '@insula/api-contracts';

/** The `multihost` block a catalog manifest declares, verbatim. */
export interface MultihostCapability {
  readonly server: string;
  readonly web_root: string;
  readonly sites_root: string;
  readonly config_dir: string;
  readonly common_include: string;
  readonly listen: number;
  readonly validate: readonly string[];
  readonly reload: readonly string[];
}

/** The subset of an `ingress_routes` row that decides what a site looks like. */
export interface SiteRoute {
  readonly id: string;
  readonly hostname: string;
  readonly path: string;
  readonly wwwRedirect: 'none' | 'add-www' | 'remove-www';
  readonly siteFolder: string;
}

export interface RenderedSite {
  readonly routeId: string;
  /** ConfigMap key = filename inside the include directory. */
  readonly filename: string;
  readonly content: string;
  /** Hostname the container will actually match on. */
  readonly serverName: string;
  readonly serverAlias: string | null;
  readonly documentRoot: string;
}

export interface SkippedSite {
  readonly routeId: string;
  readonly reason: string;
}

export interface RenderResult {
  /** ConfigMap `data`, ready to apply. */
  readonly files: Record<string, string>;
  readonly sites: readonly RenderedSite[];
  /** Routes deliberately not rendered, each with an operator-readable reason. */
  readonly skipped: readonly SkippedSite[];
}

/**
 * A hostname safe to write into a config file. Deliberately stricter than the
 * platform's hostname validation: this rejects everything that is not a
 * DNS-shaped label sequence with an optional leading `*.`, so no quote,
 * whitespace, newline or directive separator can survive into the output.
 */
const SAFE_HOSTNAME = /^(\*\.)?[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)*$/;

function isWildcard(host: string): boolean {
  return host.startsWith('*.');
}

/**
 * ServerName for a wildcard site.
 *
 * Apache requires a ServerName and will not accept a wildcard as one, but the
 * obvious substitute — the wildcard's own base, `apps.example.test` for
 * `*.apps.example.test` — would silently CLAIM that bare hostname, which may
 * be a different route pointing somewhere else entirely. A name in the
 * reserved `.invalid` TLD (RFC 2606) can never be requested, so the vhost is
 * reachable only through its ServerAlias. `UseCanonicalName Off` in the shared
 * include means PHP still reports the visitor's real host, never this one.
 */
export function syntheticServerName(routeId: string): string {
  return `route-${routeId}.multihost.invalid`;
}

/** ConfigMap key for a route. `.conf` so the image's include glob matches it. */
export function siteFilename(routeId: string): string {
  return `route-${routeId}.conf`;
}

function renderApacheVhost(
  cap: MultihostCapability,
  site: { serverName: string; serverAlias: string | null; documentRoot: string; hostname: string; routeId: string },
): string {
  const alias = site.serverAlias ? `    ServerAlias ${site.serverAlias}\n` : '';
  return [
    `# Route ${site.routeId} — ${site.hostname}`,
    '# Generated by the Insula platform. Edits here are overwritten on the next',
    '# route change; the folder a hostname serves is a property of the route.',
    `<VirtualHost *:${cap.listen}>`,
    `    ServerName ${site.serverName}`,
    alias.replace(/\n$/, ''),
    `    DocumentRoot "${site.documentRoot}"`,
    `    Include ${cap.common_include}`,
    '</VirtualHost>',
    '',
  ].filter((l) => l !== '').join('\n');
}

/**
 * Render every route that names a folder into one config file each.
 *
 * A route is SKIPPED rather than rendered when it cannot be expressed safely.
 * Skipping is reported, never silent: a site that does not appear in the
 * output falls through to the deployment's stock document root, which looks
 * exactly like a working catch-all and would otherwise hide the mistake.
 */
export function renderSites(
  cap: MultihostCapability,
  routes: readonly SiteRoute[],
): RenderResult {
  if (cap.server !== 'apache') {
    // Total over the declared enum on purpose. A capability block naming a
    // flavour with no renderer must fail loudly here rather than emit an empty
    // ConfigMap, which would read as "this deployment has no sites".
    throw new Error(
      `multihost: no renderer for server flavour '${cap.server}' (supported: apache)`,
    );
  }

  const files: Record<string, string> = {};
  const sites: RenderedSite[] = [];
  const skipped: SkippedSite[] = [];
  // Matchers already claimed, so a second route cannot quietly shadow a first.
  const claimed = new Map<string, string>();

  // Deterministic order: the ConfigMap must be byte-identical for identical
  // input or every reconcile looks like a change and reloads the server.
  const ordered = [...routes].sort((a, b) => a.id.localeCompare(b.id));

  for (const route of ordered) {
    const { canonical } = wwwRedirectHosts(route.hostname, route.wwwRedirect);

    if (route.path !== '/') {
      // A vhost is keyed by hostname; there is no path in the matcher. Serving
      // a folder for `example.com/blog` would silently serve it for the whole
      // of example.com. Refuse instead of surprising the tenant.
      skipped.push({
        routeId: route.id,
        reason: `Route path is '${route.path}'. A site folder applies to a whole hostname, so it can only be set on a route with path '/'.`,
      });
      continue;
    }

    if (!SAFE_HOSTNAME.test(canonical)) {
      skipped.push({
        routeId: route.id,
        reason: `Hostname '${canonical}' is not a plain DNS name and cannot be written into web-server config.`,
      });
      continue;
    }

    const folderIssue = folderProblem(route.siteFolder);
    if (folderIssue) {
      skipped.push({ routeId: route.id, reason: folderIssue });
      continue;
    }

    const previous = claimed.get(canonical);
    if (previous) {
      skipped.push({
        routeId: route.id,
        reason: `Hostname '${canonical}' is already served by route ${previous} on this deployment. Two routes cannot serve the same hostname from different folders.`,
      });
      continue;
    }
    claimed.set(canonical, route.id);

    const wildcard = isWildcard(canonical);
    const serverName = wildcard ? syntheticServerName(route.id) : canonical;
    const serverAlias = wildcard ? canonical : null;
    const documentRoot = `${cap.sites_root}/${route.siteFolder}`;

    const filename = siteFilename(route.id);
    files[filename] = renderApacheVhost(cap, {
      serverName,
      serverAlias,
      documentRoot,
      hostname: route.hostname,
      routeId: route.id,
    });
    sites.push({ routeId: route.id, filename, content: files[filename], serverName, serverAlias, documentRoot });
  }

  return { files, sites, skipped };
}
