/**
 * Shared "auto-managed" Secret predicate (DR-bundle bundle-everything redesign).
 *
 * Single source of truth for the rule "should this Secret be EXCLUDED
 * from the DR bundle entirely (because some controller owns it and
 * regenerates it on demand)?". Consumed by:
 *
 *   - `secrets-bundle.ts` — at export time, skip Secrets where this
 *     returns `{denied: true}`. They never enter the tar.
 *   - `secrets-audit.ts` — at classification time, the `denied` bucket
 *     in the audit UI reflects this same predicate.
 *   - `scripts/lib/secrets-denylist.jq` (mirror) — bootstrap.sh + the
 *     nightly CronJob filter via jq using the same rules. Parity is
 *     enforced by `scripts/integration-secrets-bundle.sh` Phase 1
 *     and the `scripts/ci-secrets-denylist-check.sh` CI guard.
 *
 * Rules (in priority order, first match wins):
 *
 *   1. type `kubernetes.io/service-account-token` — auto-rotated by
 *      kube-controller-manager.
 *   2. type `kubernetes.io/dockercfg` / `dockerconfigjson` —
 *      auto-generated for ServiceAccounts.
 *   3. name prefix `sh.helm.release.v1.` — Helm release state,
 *      recreatable from chart values + the cluster's helm install.
 *   4. ownerReference.kind=`Certificate` AND apiVersion contains
 *      `cert-manager.io` — cert-manager issues these from a
 *      Certificate CR; restoring them creates ownership conflicts.
 *   5. ownerReference.kind=`SealedSecret` — unsealed copies are
 *      regenerated from the SealedSecret CR.
 *   6. ownerReference.kind=`Cluster` AND apiVersion contains
 *      `postgresql.cnpg.io` — CNPG operator regenerates them from
 *      the Cluster CR.
 *
 * Everything else is bundled, with classification metadata used at
 * restore time to decide whether to apply (see restore profiles).
 */

export interface OwnerRef {
  readonly kind?: string;
  readonly apiVersion?: string;
}

export interface DenylistDecision {
  /** True when this Secret should NOT enter the bundle. */
  readonly denied: boolean;
  /** Operator-readable reason. Stable strings; consumed by the UI
   *  and the integration harness. */
  readonly reason: string;
}

export interface DenylistInput {
  readonly name: string;
  readonly type: string;
  readonly owner: OwnerRef | null;
}

const REASON_SA_TOKEN = 'ServiceAccount token (auto-rotated by k8s)';
const REASON_DOCKERCFG = 'Docker registry pull-secret (auto-generated)';
const REASON_HELM_STATE = 'Helm release state (recreatable from chart values)';
const REASON_CERT_MANAGER = 'cert-manager TLS (auto-issued from Certificate CR)';
const REASON_SEALED_SECRET = 'unsealed copy owned by SealedSecret (regenerated from seal)';
const REASON_CNPG = 'CNPG-managed (regenerated by the operator)';
const REASON_NOT_AUTO_MANAGED = 'not auto-managed';

/** Pure-function denylist check. No IO. Exported for unit testing. */
export function isAutoManaged(input: DenylistInput): DenylistDecision {
  const { name, type, owner } = input;

  if (type === 'kubernetes.io/service-account-token') {
    return { denied: true, reason: REASON_SA_TOKEN };
  }
  if (type === 'kubernetes.io/dockercfg' || type === 'kubernetes.io/dockerconfigjson') {
    return { denied: true, reason: REASON_DOCKERCFG };
  }
  if (name.startsWith('sh.helm.release.v1.')) {
    return { denied: true, reason: REASON_HELM_STATE };
  }
  if (owner) {
    const kind = owner.kind ?? '';
    const api = owner.apiVersion ?? '';
    if (kind === 'Certificate' && api.includes('cert-manager.io')) {
      return { denied: true, reason: REASON_CERT_MANAGER };
    }
    if (kind === 'SealedSecret') {
      return { denied: true, reason: REASON_SEALED_SECRET };
    }
    if (kind === 'Cluster' && api.includes('postgresql.cnpg.io')) {
      return { denied: true, reason: REASON_CNPG };
    }
  }

  return { denied: false, reason: REASON_NOT_AUTO_MANAGED };
}

/** All stable reason strings, exposed for CI guard tests to assert
 *  no drift between this module and the jq filter's `reason` field. */
export const DENYLIST_REASONS = {
  SA_TOKEN: REASON_SA_TOKEN,
  DOCKERCFG: REASON_DOCKERCFG,
  HELM_STATE: REASON_HELM_STATE,
  CERT_MANAGER: REASON_CERT_MANAGER,
  SEALED_SECRET: REASON_SEALED_SECRET,
  CNPG: REASON_CNPG,
  NOT_AUTO_MANAGED: REASON_NOT_AUTO_MANAGED,
} as const;
