#!/usr/bin/env bash
# DR bundle drift guard. Fails when the dr-sidecars.ts serialiser's
# field count for backup_configurations or backup_target_assignments
# diverges from the Drizzle schema's column count. This catches the
# common drift class: a contributor adds a new column to a backup-
# related table, doesn't update the dr-rows.json serialiser, and Unit
# B's restore importer silently misses a field on every row in every
# future bundle.
#
# The guard also asserts DR_BUNDLE_VERSION matches across all the
# consumers — bumps must be explicit in the PR that adds them.
#
# Pure grep + counting; no TypeScript runtime needed.

set -euo pipefail

REPO_ROOT=$(cd "$(dirname "$0")/.." && pwd)
cd "$REPO_ROOT"

SCHEMA="backend/src/db/schema.ts"
SERIALIZER="backend/src/modules/system-backup/dr-sidecars.ts"
CONTRACT="packages/api-contracts/src/system-backup.ts"

FAIL=0

# ─── Count columns on the table block in schema.ts ───────────────────
# Finds the `export const <tableName> = pgTable('<sqlName>', {` opener
# and counts each top-level field key inside until the closing `});`.
count_table_columns() {
  local table_name=$1
  # awk slice between the named table opener and its closing `});`.
  # Inside that slice, count lines whose first non-whitespace token is
  # a valid JS identifier followed by `:` — that's a field declaration.
  # Skip pure comment lines.
  awk -v tn="$table_name" '
    $0 ~ "^export const " tn " = pgTable\\(" { in_table=1; next }
    in_table && /^}\)/ { in_table=0; exit }
    in_table {
      # Strip trailing comments
      sub(/\/\/.*$/, "")
      # Pure-comment lines (block comments handled crudely)
      if ($0 ~ /^[[:space:]]*\/\*/) next
      if ($0 ~ /^[[:space:]]*\*/) next
      # A field declaration looks like:   ^\s*<ident>:
      if ($0 ~ /^[[:space:]]*[a-zA-Z_][a-zA-Z0-9_]*:[[:space:]]/) cnt++
    }
    END { print cnt+0 }
  ' "$SCHEMA"
}

# ─── Count fields the serialiser maps for a given table ──────────────
# The dr-sidecars.ts builder maps every column we want to include via
# `<jsField>: r.<jsField> ?? null` or similar. We count the keys in the
# object-literal returned for each table.
count_serializer_fields() {
  local marker=$1
  # The marker is a unique-in-file string that introduces the mapper.
  # We count lines until the closing `}))` that have the shape
  # `^\s*<ident>:`. Comment lines are skipped.
  awk -v m="$marker" '
    index($0, m) > 0 { in_map=1; next }
    in_map && /^[[:space:]]*\}\)\)/ { in_map=0; exit }
    in_map {
      sub(/\/\/.*$/, "")
      if ($0 ~ /^[[:space:]]*\/\*/) next
      if ($0 ~ /^[[:space:]]*\*/) next
      if ($0 ~ /^[[:space:]]*[a-zA-Z_][a-zA-Z0-9_]*:[[:space:]]/) cnt++
    }
    END { print cnt+0 }
  ' "$SERIALIZER"
}

# ─── Count fields on the Zod schema for a given const name ───────────
count_zod_fields() {
  local schema_name=$1
  awk -v n="$schema_name" '
    $0 ~ "^export const " n " = z\\.object\\(\\{" { in_obj=1; next }
    in_obj && /^\}\);/ { in_obj=0; exit }
    in_obj {
      sub(/\/\/.*$/, "")
      if ($0 ~ /^[[:space:]]*\/\*/) next
      if ($0 ~ /^[[:space:]]*\*/) next
      if ($0 ~ /^[[:space:]]*[a-zA-Z_][a-zA-Z0-9_]*:[[:space:]]/) cnt++
    }
    END { print cnt+0 }
  ' "$CONTRACT"
}

# ─── backup_configurations parity ────────────────────────────────────
# The serialiser intentionally omits 10 columns:
#   - createdAt, updatedAt (regenerated by INSERT)
#   - lastTestedAt, lastTestStatus (test-result state — doesn't travel)
#   - 6 lastSpeedtest* columns (speedtest result — doesn't travel)
# Every other column MUST appear in the serialiser. Bump this number
# alongside the exclusion list if the policy changes.
EXCLUDED_COL_COUNT=10

SCHEMA_COLS=$(count_table_columns 'backupConfigurations')
SER_FIELDS=$(count_serializer_fields 'backupConfigurations: configRows.map')
ZOD_FIELDS=$(count_zod_fields 'backupConfigurationRowSchema')

EXPECTED_SER=$((SCHEMA_COLS - EXCLUDED_COL_COUNT))
if [[ "$SER_FIELDS" -ne "$EXPECTED_SER" ]]; then
  echo "❌ ci-dr-bundle-check: backup_configurations field count drift" >&2
  echo "   Drizzle schema columns:     $SCHEMA_COLS" >&2
  echo "   dr-sidecars serialiser:     $SER_FIELDS  (expected $EXPECTED_SER = schema - $EXCLUDED_COL_COUNT excluded)" >&2
  echo "   Update backend/src/modules/system-backup/dr-sidecars.ts:buildDrRows" >&2
  echo "   AND packages/api-contracts/src/system-backup.ts:backupConfigurationRowSchema" >&2
  echo "   to include the new column." >&2
  FAIL=1
fi
if [[ "$ZOD_FIELDS" -ne "$SER_FIELDS" ]]; then
  echo "❌ ci-dr-bundle-check: backup_configurations Zod/serialiser drift" >&2
  echo "   Zod schema fields:          $ZOD_FIELDS" >&2
  echo "   dr-sidecars serialiser:     $SER_FIELDS" >&2
  echo "   The Zod schema must match the serialiser field count." >&2
  FAIL=1
fi

# ─── DR_BUNDLE_VERSION must equal 1 (bumps land in explicit PRs) ─────
VERSION_LINE=$(grep -E "^export const DR_BUNDLE_VERSION" "$CONTRACT" || true)
if [[ -z "$VERSION_LINE" ]]; then
  echo "❌ ci-dr-bundle-check: DR_BUNDLE_VERSION constant not exported from $CONTRACT" >&2
  FAIL=1
elif ! echo "$VERSION_LINE" | grep -q '= 1;'; then
  echo "❌ ci-dr-bundle-check: DR_BUNDLE_VERSION is not 1." >&2
  echo "   $VERSION_LINE" >&2
  echo "   Version bumps require an explicit migration plan + reader-side handling." >&2
  echo "   If you're intentionally bumping, update this CI guard alongside the" >&2
  echo "   bump (and add a migration note to docs/04-deployment/DR_BUNDLE_ROADMAP.md)." >&2
  FAIL=1
fi

# ─── Critical-secret list must be non-empty ──────────────────────────
TIERS="backend/src/modules/system-backup/secrets-tiers.ts"
if ! grep -q "CRITICAL_TIER_1_SECRETS" "$TIERS"; then
  echo "❌ ci-dr-bundle-check: CRITICAL_TIER_1_SECRETS export missing from $TIERS" >&2
  FAIL=1
fi
for crit in 'platform/platform-secrets' 'platform/backup-target-key'; do
  if ! grep -q "'$crit'" "$TIERS"; then
    echo "❌ ci-dr-bundle-check: CRITICAL_TIER_1_SECRETS missing '$crit' — bundle would be unrestorable without it" >&2
    FAIL=1
  fi
done

if [[ $FAIL -ne 0 ]]; then exit 1; fi
echo "✅ ci-dr-bundle-check: schema parity OK, DR_BUNDLE_VERSION=1, critical Secrets listed."
echo "   backup_configurations: $SCHEMA_COLS schema cols / $SER_FIELDS serialiser / $ZOD_FIELDS Zod"
