#!/usr/bin/env bash
#
# CI guard — every notification delivery channel must ship a template for
# every category. A channel with no templates behind it delivers nothing.
#
# Why this guard exists
# ---------------------
# 2026-08-26 added the `ntfy` push channel: an enum entry in
# NOTIFICATION_CHANNEL_ID, four columns on `notification_providers`, a
# publisher, a pg-boss worker, a dispatcher leg, an admin UI card and an
# e2e spec. What it did not add was a single template row.
#
# Nothing failed. The dispatcher quietly rendered the category's `in_app`
# body instead, so pushes did go out — but ntfy was the only channel whose
# text an operator could not edit, preview, version or restore, and
# Settings → Notifications → Templates listed zero rows for it. The
# existing unit guard could not see this: it opened with
#
#     if (channel !== 'in_app' && channel !== 'email') continue;
#
# so it was structurally incapable of failing for a third channel — an
# audit whose selector cannot match its target reads exactly like a clean
# bill of health.
#
# The same guard also only demanded a template for channels a category
# listed in its SEED `defaultChannels`. That list is operator-editable at
# runtime (PATCH /admin/notifications/categories/:id takes any subset of
# the enum), so it is a default, not a bound. `tls.certificate_issued`
# seeded `['in_app']` and had no email template at all — one toggle in the
# admin UI away from silently delivering nothing.
#
# What is checked
# ---------------
# This runs the real TypeScript seed data through node rather than
# grepping it: ~30% of the template rows are generated by `.flatMap()`
# blocks, and a regex over the source undercounts them badly (measured:
# 75 of 99 rows). A guard that reads the file with a pattern would report
# false gaps for the generated categories and could be "fixed" by
# loosening the pattern until it matched nothing.
#
#   1. Every (category × channel × 'en') tuple has exactly one seed row.
#   2. Every channel in NOTIFICATION_CHANNEL_ID reaches 100% of categories.
#   3. The unit guard still exists and still iterates the contract enum
#      (deleting or narrowing it is itself a failure).
#
# Compile-time companion: CHANNEL_SEED_STRATEGY in seed-data.ts is
#   Record<NotificationChannelId, …>, so a new channel fails `tsc` first.
# Unit companion: backend/src/modules/notifications/seed-consistency.test.ts
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

CATEGORIES="$REPO_ROOT/backend/src/modules/notifications/categories/seed.ts"
TEMPLATES="$REPO_ROOT/backend/src/modules/notifications/templates/seed-data.ts"
UNIT_GUARD="$REPO_ROOT/backend/src/modules/notifications/seed-consistency.test.ts"
CONTRACTS="$REPO_ROOT/packages/api-contracts/src/notification-categories.ts"

fail=0
err() { printf 'FAIL: %s\n' "$*" >&2; fail=1; }

echo "── notification template coverage guard ────────────────────────────"

for f in "$CATEGORIES" "$TEMPLATES" "$UNIT_GUARD" "$CONTRACTS"; do
  [ -f "$f" ] || { err "missing $f"; exit 1; }
done

# ── 1. The unit guard must still cover the whole enum ───────────────────
#
# The coverage assertions live in vitest; this script's job is to make
# sure they cannot be quietly narrowed back to a two-channel subset the
# way they were the first time.
#
# Every check below reads CODE ONLY. Both files document the old broken
# pattern verbatim so the next reader understands the failure, and a
# naive grep matches that prose — the guard would fail on its own
# explanation, then get "fixed" by deleting the explanation.
code_only() { grep -vE '^[[:space:]]*(\*|//|/\*)' "$1"; }

if code_only "$UNIT_GUARD" | grep -qE "channel !== 'in_app'"; then
  err "$UNIT_GUARD re-introduces the in_app/email channel exclusion."
  echo "     That exclusion is why the ntfy channel shipped with no templates." >&2
fi
if ! code_only "$UNIT_GUARD" | grep -q 'NOTIFICATION_CHANNEL_ID'; then
  err "$UNIT_GUARD no longer iterates NOTIFICATION_CHANNEL_ID."
  echo "     The matrix must be driven off the contract enum, not a local list." >&2
fi
# Match the DECLARATION, not a mention: the header comment names this
# symbol too, so a bare substring check would pass over a deleted Record.
if ! grep -qE 'const CHANNEL_SEED_STRATEGY: Record<NotificationChannelId,' "$TEMPLATES"; then
  err "$TEMPLATES no longer declares CHANNEL_SEED_STRATEGY as a total Record."
  echo "     Record<NotificationChannelId, …> is the compile-time half of this" >&2
  echo "     guard: without it, a new channel no longer fails tsc." >&2
fi

# ── 2. Run the real seed data ───────────────────────────────────────────
#
# tsc is not available in every job that wants this guard, and the seed
# files are plain data — node's type-stripping loader is enough. Both
# import only `type` from @insula/api-contracts, which strips away, so no
# npm install and no build of the contracts package is required.
#
# The contracts file itself is the exception: it imports zod at RUNTIME,
# so it is read as TEXT and the enum pulled from its single literal line.
# That is the one parse in this script, it is kept to one line, and it is
# validated below — an unparsed or empty enum aborts rather than quietly
# checking a matrix with no columns.
TMP_OUT="$(mktemp)"
trap 'rm -f "$TMP_OUT"' EXIT

CATEGORIES="$CATEGORIES" TEMPLATES="$TEMPLATES" CONTRACTS="$CONTRACTS" \
node --experimental-strip-types --no-warnings --input-type=module -e '
import { readFileSync } from "node:fs";

const cats = await import(process.env.CATEGORIES);
const tpls = await import(process.env.TEMPLATES);

const ALL_CATEGORIES = cats.ALL_CATEGORIES;
const ALL_SEED_TEMPLATES = tpls.ALL_SEED_TEMPLATES;
const LOCALE = "en";

// NOTIFICATION_CHANNEL_ID = ["in_app", "email", "ntfy"] as const;
const src = readFileSync(process.env.CONTRACTS, "utf8");
const m = src.match(/NOTIFICATION_CHANNEL_ID\s*=\s*\[([^\]]*)\]\s*as const/);
if (!m) {
  console.error("FAIL: could not read NOTIFICATION_CHANNEL_ID from " + process.env.CONTRACTS);
  console.error("      The declaration moved or changed shape. Fix this parse —");
  console.error("      do NOT let the guard fall back to a hardcoded channel list.");
  process.exit(1);
}
const CHANNELS = [...m[1].matchAll(/[\x27\x22]([a-z_]+)[\x27\x22]/g)].map((x) => x[1]);

if (!Array.isArray(ALL_CATEGORIES) || ALL_CATEGORIES.length === 0) {
  console.error("FAIL: ALL_CATEGORIES is empty — a guard over nothing passes trivially.");
  process.exit(1);
}
if (CHANNELS.length === 0) {
  console.error("FAIL: parsed an EMPTY channel list — every check below would pass vacuously.");
  process.exit(1);
}
// Cross-check the parse against reality: any channel the seed data already
// uses must have come out of the enum. If the regex silently under-matched,
// this catches it instead of reporting full coverage of a short list.
const seeded = [...new Set(ALL_SEED_TEMPLATES.map((t) => t.channel))];
const unparsed = seeded.filter((c) => !CHANNELS.includes(c));
if (unparsed.length) {
  console.error("FAIL: seed data uses channel(s) absent from the parsed enum: " + unparsed.join(", "));
  console.error("      The NOTIFICATION_CHANNEL_ID parse is under-matching.");
  process.exit(1);
}

const key = (c, ch) => c + "|" + ch;
const counts = new Map();
for (const t of ALL_SEED_TEMPLATES) {
  if (t.locale !== LOCALE) continue;
  const k = key(t.categoryId, t.channel);
  counts.set(k, (counts.get(k) ?? 0) + 1);
}

const missing = [];
const dupes = [];
for (const cat of ALL_CATEGORIES) {
  for (const ch of CHANNELS) {
    const n = counts.get(key(cat.id, ch)) ?? 0;
    if (n === 0) missing.push(cat.id + " -> " + ch);
    else if (n > 1) dupes.push(cat.id + " -> " + ch + " (x" + n + ")");
  }
}

const perChannel = CHANNELS.map((ch) => {
  const covered = new Set(
    ALL_SEED_TEMPLATES.filter((t) => t.channel === ch && t.locale === LOCALE).map((t) => t.categoryId),
  );
  return { ch, covered: covered.size };
});

console.log("  categories: " + ALL_CATEGORIES.length
  + " | channels: " + CHANNELS.join(", ")
  + " | seed rows: " + ALL_SEED_TEMPLATES.length);
for (const { ch, covered } of perChannel) {
  console.log("    " + ch.padEnd(8) + covered + "/" + ALL_CATEGORIES.length + " categories");
}

let bad = 0;
if (missing.length) {
  bad = 1;
  console.error("FAIL: " + missing.length + " (category, channel) pair(s) have no seed template.");
  console.error("      The dispatcher drops these with `no_template` — an enabled");
  console.error("      channel that delivers silence. Add them in seed-data.ts.");
  for (const m of missing.slice(0, 40)) console.error("        " + m);
  if (missing.length > 40) console.error("        … and " + (missing.length - 40) + " more");
}
if (dupes.length) {
  bad = 1;
  console.error("FAIL: duplicate seed rows (the last one silently wins at seed time):");
  for (const d of dupes) console.error("        " + d);
}
process.exit(bad);
' > "$TMP_OUT" 2>&1 || fail=1
cat "$TMP_OUT"

if [ "$fail" -ne 0 ]; then
  echo "── notification template coverage guard: FAILED ────────────────────" >&2
  exit 1
fi
echo "ci-notification-template-coverage: OK — full (category × channel) matrix covered."
