#!/usr/bin/env bash
#
# CI guard — the payload<->template variable contract, checked BOTH ways.
#
# Why this guard exists
# ---------------------
# `subscriptions/service.ts` supplied `newExpiresAt`. All three
# `subscription.renewed` templates read `{{nextBillingAt}}`. The names never
# matched, and under Handlebars strict mode that one mismatch failed in two
# different ways — neither of which raised anything:
#
#   {{nextBillingAt}}              THROWS  -> delivery row marked `skipped`,
#                                            not `failed`, so no alert and no
#                                            retry. 16 emails never sent.
#   {{#if nextBillingAt}}…{{/if}}  renders '' -> the in-app message silently
#                                                lost its date.
#
# The first report came from a customer, months later. Production had 16
# `render_failed` rows the whole time, in a column nobody queries.
#
# What is checked
# ---------------
#   1. MISSING — a template references a variable no emitter supplies.
#      These either drop a delivery or quietly strip a fact.
#   2. UNUSED  — an emitter supplies a variable no template renders. The data
#      was gathered and thrown away: `subscription.changed` collects the old
#      and new plan names and renders "Your subscription was modified."
#
# Both directions matter. A one-way check would have passed `subscription.changed`.
#
# The seed data is executed through node's type-stripping loader rather than
# grepped: ~30% of template rows are generated by `.flatMap()` blocks and a
# regex over the source undercounts them badly. The SAME extraction runs in
# production (`templates/variables.ts`), so CI and runtime cannot disagree
# about what a template asks for.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

CATEGORIES="$REPO_ROOT/backend/src/modules/notifications/categories/seed.ts"
TEMPLATES="$REPO_ROOT/backend/src/modules/notifications/templates/seed-data.ts"
EVENTS="$REPO_ROOT/backend/src/modules/notifications/events.ts"

echo "── notification variable-contract guard ─────────────────────────────"

for f in "$CATEGORIES" "$TEMPLATES" "$EVENTS"; do
  [ -f "$f" ] || { echo "FAIL: missing $f" >&2; exit 1; }
done

# ALLOWLIST — categories whose mismatch is known and deliberately accepted.
# Keep this SHORT and justify every entry. An entry here is a promise that the
# gap is intentional, not a place to silence the guard.
#
#   legacy.*  — the retiring `notifyUser()` path passes title/message at the
#               call site rather than through a typed payload. Removed with
#               the path itself (phase 9 of the overhaul).
ALLOW_MISSING="legacy.info legacy.warning legacy.error legacy.success"

CATEGORIES="$CATEGORIES" TEMPLATES="$TEMPLATES" EVENTS="$EVENTS" \
ALLOW_MISSING="$ALLOW_MISSING" \
node --experimental-strip-types --no-warnings --input-type=module -e '
import { readFileSync } from "node:fs";

const tpls = await import(process.env.TEMPLATES);
const cats = await import(process.env.CATEGORIES);
const EVENTS_SRC = readFileSync(process.env.EVENTS, "utf8");
const ALLOW_MISSING = new Set((process.env.ALLOW_MISSING ?? "").split(/\s+/).filter(Boolean));

const ALL_CATEGORIES = cats.ALL_CATEGORIES;
const ALL_SEED_TEMPLATES = tpls.ALL_SEED_TEMPLATES;

if (!Array.isArray(ALL_CATEGORIES) || ALL_CATEGORIES.length === 0) {
  console.error("FAIL: ALL_CATEGORIES is empty — a guard over nothing passes trivially.");
  process.exit(1);
}
if (!Array.isArray(ALL_SEED_TEMPLATES) || ALL_SEED_TEMPLATES.length === 0) {
  console.error("FAIL: ALL_SEED_TEMPLATES is empty — a guard over nothing passes trivially.");
  process.exit(1);
}

// Must stay identical to templates/variables.ts:REF_RE. Block helpers are
// included deliberately: {{#if x}} is the form that fails SILENTLY, so a
// matcher without it would report a clean contract for exactly the template
// that drops data.
const REF_RE = /\{\{\{?\s*(?:#(?:if|unless)\s+)?([A-Za-z_][\w.]*)\s*\}?\}\}/g;
const RESERVED = new Set(["else", "this"]);
const DISPATCHER_PROVIDED = new Set(["platformName", "userName", "tenantName", "contactName", "occurredAt"]);

// STRUCTURAL keys are carried for routing/linking, never for rendering, so
// "no template reads it" is the correct state rather than a defect. Keep this
// set TINY and justify each entry — it is the one way to silence the UNUSED
// arm of this guard, and a growing list means the guard is being worked
// around rather than satisfied.
//
//   subjectLabels — the raw Prometheus label set behind an SLO alert. It is a
//     Record, not a string; templates render the humanised `subject` instead.
//     It exists so a surface can build a deep link to the offending object.
const STRUCTURAL = new Set(["subjectLabels"]);

function refs(text) {
  if (!text) return [];
  const out = new Set();
  for (const m of text.matchAll(REF_RE)) {
    const root = m[1].split(".")[0];
    if (!RESERVED.has(root)) out.add(root);
  }
  return [...out];
}

// Payload interfaces, and which category each helper dispatches.
const interfaces = new Map();
for (const m of EVENTS_SRC.matchAll(/export interface (\w+Payload)\s*\{([\s\S]*?)\n\}/g)) {
  interfaces.set(m[1], [...m[2].matchAll(/^\s*readonly\s+(\w+)\??:/gm)].map((f) => f[1]));
}
// Category-id lookup tables, e.g.
//   const OPERATIONAL_CATEGORY = { storage: 'admin.storage_event', … } as const;
// A helper that dispatches through one of these names no category literal in
// its own body, so without this the guard reports every such category as
// having no emitter — which is a false finding, not a real one.
const CATEGORY_MAPS = new Map();
for (const m of EVENTS_SRC.matchAll(/const (\w+) = \{([\s\S]*?)\} as const;/g)) {
  const ids = [...m[2].matchAll(/[\x27\x22]([a-z_]+\.[a-z_]+)[\x27\x22]/g)].map((x) => x[1]);
  if (ids.length) CATEGORY_MAPS.set(m[1], ids);
}

const supplied = new Map();
for (const m of EVENTS_SRC.matchAll(/export async function (\w+)\(([\s\S]*?)\): Promise<void> \{([\s\S]*?)\n\}/g)) {
  const payloadType = (m[2].match(/payload:\s*(\w+Payload)/) || [])[1];
  const keys = payloadType ? (interfaces.get(payloadType) ?? []) : [];
  const cats = [...m[3].matchAll(/[\x27\x22]([a-z_]+\.[a-z_]+)[\x27\x22]/g)].map((x) => x[1]);
  for (const [mapName, ids] of CATEGORY_MAPS) {
    if (m[3].includes(mapName)) cats.push(...ids);
  }
  for (const c of new Set(cats)) {
    supplied.set(c, new Set([...(supplied.get(c) ?? []), ...keys]));
  }
}

if (interfaces.size === 0 || supplied.size === 0) {
  console.error("FAIL: parsed ZERO payload interfaces or ZERO dispatching helpers from events.ts.");
  console.error("      The parse broke — fix it; do NOT let the guard pass over an empty set.");
  process.exit(1);
}

let fail = 0;
for (const cat of ALL_CATEGORIES) {
  const mine = ALL_SEED_TEMPLATES.filter((t) => t.categoryId === cat.id && t.locale === "en");
  if (mine.length === 0) continue;

  const referenced = new Set();
  for (const t of mine) {
    for (const v of [...refs(t.subjectTemplate), ...refs(t.bodyTemplate)]) referenced.add(v);
  }
  const have = supplied.get(cat.id) ?? new Set();

  const missing = [...referenced].filter((v) => !DISPATCHER_PROVIDED.has(v) && !have.has(v));
  const unused = [...have].filter((v) => !referenced.has(v) && !STRUCTURAL.has(v));

  if (missing.length && !ALLOW_MISSING.has(cat.id)) {
    fail = 1;
    console.error(`FAIL ${cat.id}: template reads variable(s) nobody supplies: ${missing.join(", ")}`);
    for (const t of mine) {
      const text = `${t.subjectTemplate ?? ""}\n${t.bodyTemplate}`;
      for (const v of missing) {
        if (new RegExp(`\\{\\{\\{?\\s*${v}\\s*\\}?\\}\\}`).test(text)) {
          console.error(`     ${t.channel}: bare {{${v}}} — renders a placeholder and degrades the message`);
        }
      }
    }
  }
  if (unused.length) {
    fail = 1;
    console.error(`FAIL ${cat.id}: emitter supplies variable(s) no template renders: ${unused.join(", ")}`);
    console.error("     The data is gathered and thrown away. Render it or stop collecting it.");
  }
}

if (fail) {
  console.error("");
  console.error("A payload<->template mismatch is not cosmetic: it either degrades the");
  console.error("message or silently discards a fact the emitter went and fetched.");
  process.exit(1);
}
console.log(`OK: ${ALL_CATEGORIES.length} categories, ${ALL_SEED_TEMPLATES.length} templates — variable contract holds both ways.`);
'
