#!/usr/bin/env bash
# ci-server-generated-credentials-check.sh — the panels must never generate a
# credential they then display.
#
# WHY: both tenant-panel database screens generated a password in the browser,
# sent it to the API, and displayed the value they had generated. The API
# ignored the submitted value and applied its own — so EVERY database user
# created through the panel had a password nobody had ever seen. The only
# symptom was "Access denied" from the tenant's own application, with correct
# grants and a correct username, which is close to undiagnosable from the UI.
#
# It was finally identified from the charset: the panel's generator included
# `!@#$%^&*`, the server's is [a-zA-Z0-9_-], so a displayed password containing
# a symbol proved it had never been applied.
#
# Rule: credentials are generated server-side and returned in the response. The
# panel displays the response, never its own value.
#
# Exit: 0 clean · 1 a panel generates a credential locally
set -uo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT" || exit 1
fail=0

# 1. No local password/secret generator in the database screens.
offenders=$(grep -rnE "function generate(Random)?(Password|Secret|Credential)" \
  frontend/tenant-panel/src frontend/admin-panel/src 2>/dev/null \
  | grep -viE "rndc|__tests__|\.test\." || true)
if [ -n "$offenders" ]; then
  echo "ci-server-generated-credentials: panel generates a credential locally:" >&2
  echo "$offenders" | sed 's/^/  /' >&2
  echo "  Credentials are generated server-side. Display response.data.password." >&2
  fail=1
fi

# 2. The db-user mutations must not accept a password parameter — if they do,
#    a call site can send one and then display it, which is the whole bug.
if grep -nE "db-users" frontend/tenant-panel/src/hooks/use-deployments.ts 2>/dev/null \
   | grep -q .; then
  if awk '/useCreateDbUser|useSetDbUserPassword/,/^}/' frontend/tenant-panel/src/hooks/use-deployments.ts \
     | grep -qE "^\s+password: string;"; then
    echo "ci-server-generated-credentials: a db-user mutation still accepts a password argument" >&2
    echo "  Remove it — the server generates the password and returns it." >&2
    fail=1
  fi
fi

# 3. The API must REJECT a submitted password rather than silently ignore it.
for route in db-users; do
  if ! grep -q "Passwords are generated by the server" backend/src/modules/deployments/routes.ts; then
    echo "ci-server-generated-credentials: $route routes do not reject a submitted password" >&2
    fail=1
  fi
done

[ "$fail" -eq 0 ] && echo "ci-server-generated-credentials: ok"
exit "$fail"
