/**
 * F4 — Renders an ordered list of enabled WAF rule exclusions into the
 * ModSecurity .conf body that gets mounted into the modsec-crs pod.
 *
 * Pure function — no DB, no K8s, no I/O. Unit-tested in renderer.test.ts.
 *
 * Rendered file lives at:
 *   /etc/modsecurity.d/owasp-crs/rules/REQUEST-901-EXCLUSION-RULES-BEFORE-CRS-DYNAMIC.conf
 *
 * The "-BEFORE-CRS" suffix matches CRS's auto-load convention; the 901
 * sort key puts it AFTER the static 900 file (so the static file's
 * exclusions still apply first) but still BEFORE the main CRS rules so
 * the ctl: actions take effect.
 *
 * Rule ID range: 9001000-9001999 reserved for this renderer. Each row
 * occupies exactly one rule ID (sequential by row order). Static file
 * uses 9000xxx, so there's no collision risk.
 *
 * Matching mechanism: every emitted SecRule fires on
 *   REQUEST_HEADERS:X-Forwarded-Host @rx <hostnameRegex>
 * Reason: Traefik's modsecurity plugin proxies inspected requests with
 * Host=modsec-crs.traefik.svc.cluster.local — matching REQUEST_HEADERS:Host
 * never fires. See scripts/ci-modsec-exclusion-check.sh which enforces
 * this invariant on the generated conf string as well as on YAML.
 */

import { isIP } from 'node:net';
import type { WafRuleExclusion } from '@insula/api-contracts';

export const DYNAMIC_RULE_ID_BASE = 9_001_000;
export const DYNAMIC_RULE_ID_MAX = 9_001_999;

/** Single rule; own ID range so it can never collide with the per-row rules. */
export const WAF_IP_BYPASS_RULE_ID = 9_002_000;
/** Bounds the emitted @ipMatch list — a runaway allowlist must not produce a
 *  multi-KB SecRule that slows every request through the WAF. */
export const WAF_IP_BYPASS_MAX_ENTRIES = 200;

/**
 * Accept ONLY a bare IPv4/IPv6 address or CIDR.
 *
 * These values come from CrowdSec's store via `cscli`, i.e. from outside this
 * process, and are interpolated into a SecRule. Anything containing a quote,
 * backslash, comma or space could terminate the @ipMatch argument and turn the
 * rest of the line into attacker-influenced rule text. Parsing with isIP()
 * rather than a regex means nothing exotic (embedded NULs, unicode digits,
 * `1.2.3.4 "` ) can slip through: if it is not a literal address, it is
 * refused and simply not rendered.
 */
export function isRenderableIpValue(value: string): boolean {
  const parts = value.split('/');
  if (parts.length > 2) return false;
  const [addr, prefix] = parts;
  const family = isIP(addr);
  if (family === 0) return false;
  if (prefix === undefined) return true;
  if (!/^\d{1,3}$/.test(prefix)) return false;
  const bits = Number(prefix);
  return family === 4 ? bits <= 32 : bits <= 128;
}

/**
 * Render the operator IP bypass: allowlisted sources are never blocked, but
 * are still inspected and logged.
 *
 * `ctl:ruleEngine=DetectionOnly`, NOT `Off`. Every rule still evaluates and
 * still writes its match to the audit log, so an allowlisted source keeps
 * showing up in WAF Events — it simply never takes the disruptive action.
 * That preserves the forensics (you can see that an allowlisted host tripped
 * 942100 last night) while guaranteeing the operator cannot be locked out by
 * a false positive. `Off` would have made those requests invisible.
 *
 * Residual risk worth knowing: a request from an allowlisted source is not
 * stopped, so a stolen session or a compromised workstation on that IP reaches
 * the API — it is merely visible afterwards. Keep the list to specific hosts
 * and prefer /32 (or /128) over ranges.
 *
 * Matched on X-Real-Ip, NOT REMOTE_ADDR. ModSecurity sits behind Traefik, so
 * REMOTE_ADDR is the Traefik pod IP — an allowlist on it would match Traefik
 * and disable the WAF for every request on the internet. X-Real-Ip is safe to
 * trust here only because bootstrap.sh pins
 * `entryPoints.*.forwardedHeaders.trustedIPs=127.0.0.1/32`, so Traefik
 * overwrites any client-supplied value; the same reasoning the operator-trust
 * module documents. If that pin is ever widened, this rule becomes spoofable
 * and MUST be revisited.
 *
 * Country-scoped allowlist entries are skipped — @ipMatch cannot express them.
 */
export const renderIpBypass = (values: readonly string[]): string | null => {
  const safe = [...new Set(values.filter(isRenderableIpValue))].slice(0, WAF_IP_BYPASS_MAX_ENTRIES);
  if (safe.length === 0) return null;
  return [
    `# Operator IP bypass — ${safe.length} allowlisted source(s) are never`,
    '# BLOCKED, but are still inspected and still logged to WAF Events',
    '# (ctl:ruleEngine=DetectionOnly). Source of truth: the CrowdSec',
    '# `admin-panel` allowlist.',
    `SecRule REQUEST_HEADERS:X-Real-Ip "@ipMatch ${safe.join(',')}" \\`,
    `    "id:${WAF_IP_BYPASS_RULE_ID},\\`,
    '     phase:1,\\',
    '     pass,\\',
    '     nolog,\\',
    '     ctl:ruleEngine=DetectionOnly"',
  ].join('\n');
};

const HEADER = `# AUTO-GENERATED by waf-rule-exclusions reconciler.
# Do NOT edit by hand — your changes will be overwritten.
# Source of truth: waf_rule_exclusions table.
# Companion to the static REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
# from k8s/base/modsecurity-crs/exclusion-rules-configmap.yaml.
`;

const EMPTY_BODY = `${HEADER}
# No DB-rendered exclusions are currently enabled.
# Operators can add exclusions from the WAF Events tab in the
# admin panel (/settings/security-hardening).
`;

export interface RenderResult {
  readonly body: string;
  readonly count: number;
  /** Sha256 (hex) of `body` — used to detect changes and bump the
   * modsec-crs Deployment annotation. */
  readonly hash: string;
}

/**
 * Render the SecRule snippet for one exclusion.
 * Caller is responsible for ensuring rowIndex < (DYNAMIC_RULE_ID_MAX - DYNAMIC_RULE_ID_BASE).
 */
export const renderOneExclusion = (
  exclusion: Pick<WafRuleExclusion, 'ruleId' | 'hostnameRegex' | 'scope' | 'reason' | 'createdBy'>,
  rowIndex: number,
): string => {
  // Defense-in-depth: if `"` reaches the renderer despite the Zod +
  // DB CHECK guards, refuse rather than emit a broken SecRule that
  // would let the rest of the line escape the @rx string and crash
  // modsec-crs (or worse, become an attacker-controlled SecRule body).
  // Trailing backslash is blocked by the DB CHECK + Zod regexParseable.
  if (exclusion.hostnameRegex.includes('"')) {
    throw new Error(
      `waf-rule-exclusions renderer: unsafe hostnameRegex characters in row ${exclusion.ruleId} — refusing to render`,
    );
  }
  // Belt-and-braces against a row that somehow has a trailing backslash
  // (bypassing every other layer). The PCRE parser crash this prevents
  // is the cluster-wide WAF DoS the security review called out.
  if (exclusion.hostnameRegex.endsWith('\\')) {
    throw new Error(
      `waf-rule-exclusions renderer: trailing backslash in row ${exclusion.ruleId} — refusing to render (would crash modsec-crs)`,
    );
  }
  const ruleId = DYNAMIC_RULE_ID_BASE + rowIndex;
  const ctl =
    exclusion.scope === 'full_disable'
      ? `ctl:ruleRemoveById=${exclusion.ruleId}`
      : `ctl:ruleRemoveTargetById=${exclusion.ruleId};ARGS_NAMES`;

  // Multi-line comment header so operators can grep the .conf for the reason.
  // Strip any CR/LF from reason just in case (DB CHECK constraint blocks newlines,
  // but defensive belt-and-braces here).
  const safeReason = exclusion.reason.replace(/[\r\n]+/g, ' ').slice(0, 256);
  const safeCreatedBy = exclusion.createdBy.replace(/[\r\n"]+/g, '_').slice(0, 64);

  // Trailing `\\` after each line is the CRS/ModSecurity continuation marker.
  // The final line has NO trailing `\\` so the SecRule terminates.
  return [
    `# rule ${exclusion.ruleId} for ${exclusion.hostnameRegex} — ${safeReason} (by ${safeCreatedBy})`,
    `SecRule REQUEST_HEADERS:X-Forwarded-Host "@rx ${exclusion.hostnameRegex}" \\`,
    `    "id:${ruleId},\\`,
    `     phase:1,\\`,
    `     pass,\\`,
    `     nolog,\\`,
    `     ${ctl}"`,
  ].join('\n');
};

/**
 * Render all enabled exclusions into one .conf body + sha256 hash.
 *
 * Input MUST already be sorted by createdAt ASC (or any stable order) so
 * the hash is deterministic across reconciler ticks. The service layer
 * sort key is (createdAt ASC, id ASC).
 *
 * If more than (DYNAMIC_RULE_ID_MAX - DYNAMIC_RULE_ID_BASE + 1) rows
 * are passed in, throws — caller must enforce the cap at the service
 * layer (currently 1000 enabled rows).
 */
export const renderExclusions = (
  enabledExclusions: ReadonlyArray<WafRuleExclusion>,
  bypassIps: ReadonlyArray<string> = [],
): RenderResult => {
  const max = DYNAMIC_RULE_ID_MAX - DYNAMIC_RULE_ID_BASE + 1;
  if (enabledExclusions.length > max) {
    throw new Error(
      `waf-rule-exclusions renderer: ${enabledExclusions.length} exclusions exceeds reserved rule-ID range (${max})`,
    );
  }

  // Emitted FIRST: ctl:ruleEngine=Off has to be evaluated before anything
  // else in phase 1, and a bypassed request should cost nothing further.
  const bypass = renderIpBypass(bypassIps);

  if (enabledExclusions.length === 0) {
    // With no exclusions AND no bypass the body must stay byte-identical to
    // the seed ConfigMap in k8s/base — the reconciler diffs by content, so
    // any drift here would make it patch on every tick forever.
    const body = bypass === null ? EMPTY_BODY : [HEADER, '', bypass, ''].join('\n');
    return {
      body,
      count: 0,
      hash: sha256Hex(body),
    };
  }

  const parts = [HEADER, ''];
  if (bypass !== null) {
    parts.push(bypass);
    parts.push('');
  }
  for (let i = 0; i < enabledExclusions.length; i += 1) {
    parts.push(renderOneExclusion(enabledExclusions[i]!, i));
    parts.push('');
  }
  const body = parts.join('\n');
  return {
    body,
    count: enabledExclusions.length,
    hash: sha256Hex(body),
  };
};

// Local sha256 — module-scoped so renderer.ts has zero non-test imports
// other than the contracts type (which is types-only and tree-shakes
// to nothing in JS).
import { createHash } from 'node:crypto';

const sha256Hex = (input: string): string => createHash('sha256').update(input).digest('hex');
