apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  namespace: platform
data:
  environment: "staging"
  log-level: "info"
  default-storage-class: "longhorn"
  ingress-base-domain: "192.0.2.56.sslip.io"
  cluster-issuer-name: "letsencrypt-staging-http01"
  admin-url: "https://admin.192.0.2.56.sslip.io"
  client-url: "https://client.192.0.2.56.sslip.io"
  cors-origins: "https://admin.192.0.2.56.sslip.io,https://client.192.0.2.56.sslip.io"
